<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DebtLoanMortgage</name>
   <tag></tag>
   <elementGuidId>679e23b7-7c59-49a6-ba4f-c45d7c79864e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_liability_type_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_liability_type_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>271ec91f-8777-4fe3-a75d-ac2e352737ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dba10739-037b-4a28-84ed-aec3c4d8b8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>liability_type_id</value>
      <webElementGuid>f694b953-5514-471c-9475-5fdb8dc576e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_liability_type_id</value>
      <webElementGuid>96d15fd7-6b3d-4dc6-94e4-0321054fe078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>341c3aeb-da85-4dea-891a-5413e16a5351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>418d648c-b72a-486d-aefe-ba33d51c38ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DebtLoanMortgage</value>
      <webElementGuid>06c5e96a-aacd-49b0-9f84-15256ec4a8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_liability_type_id&quot;)</value>
      <webElementGuid>855066fa-c7c3-4107-aec1-f08617782b42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_liability_type_id']</value>
      <webElementGuid>5bf5fc46-3b1a-4cc1-bac3-360358ba664f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liability_type_id_holder']/div/select</value>
      <webElementGuid>00e7d502-2bef-4a5a-b7fe-323100430bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liability type'])[1]/following::select[1]</value>
      <webElementGuid>0bedb7bc-0b61-4bbc-938d-63c55d871e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::select[2]</value>
      <webElementGuid>8a38d0d4-fa2a-46eb-ba97-e529653a395f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I owe amount'])[1]/preceding::select[1]</value>
      <webElementGuid>ed6ce358-3d48-47d1-92f4-76235166cacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liability in/out'])[1]/preceding::select[1]</value>
      <webElementGuid>af72dbf0-3383-4053-9eff-7e9870b97f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>a61ce90d-5a58-4b0d-95b7-1ff1de66ebb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'liability_type_id' and @id = 'ffInput_liability_type_id' and (text() = 'DebtLoanMortgage' or . = 'DebtLoanMortgage')]</value>
      <webElementGuid>fd603329-3920-49ca-b9ea-3cd8ed964d52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
