<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GUI_Create_New_Bill</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>74db89a1-00ec-4d17-a0fa-34969daef173</testSuiteGuid>
   <testCaseLink>
      <guid>f5b588ef-fc89-4fec-9f9f-937a481da2a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ea4e54f7-4d96-42c8-8dc3-4b441688553f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>828e0421-2e34-4cd9-bd44-cd1a8e72e930</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57a856d4-49d7-4015-9055-8f52bfb589e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3418a505-34ea-46be-b561-280955b04632</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68d2ee41-8573-40a7-991d-41c51b4b504b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d7ac2e4-d9ac-40fe-8b68-85df39b5b534</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8152a96-ab47-41be-acce-bbef787ede5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd473c4a-6834-4395-9cfa-c3a06f17adaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>812537a1-7797-4638-a840-81a368677d09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ca5bd11-3d55-49fa-bb26-e18bc3fd7899</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dcbf0b9-7faa-4b82-ab6b-aa75736c9148</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>942e1384-8836-4dcc-8042-3f8f2a4ff32a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4ab4c53-dc6b-4853-b7eb-2177a2213800</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0115e0ce-35db-42d7-94b4-bf205d3f1171</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e753de9-c079-450d-af84-9b45147dcf57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccb7756b-8dbf-4588-8ebe-2095cde767a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>206a7247-a44f-4349-af44-26e6978439ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7b64a8e-39d1-4d91-9156-4c2507b11461</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6ec16f1-cecb-4f5d-8474-a00d1c93635d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e99fd4c5-bf9e-4e26-900f-bda95ff54bcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>468def90-85f3-49a0-8cd8-9e110b7869c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9b9ab89-b3a2-4a44-8f46-8b0ea785f794</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f90cf36-c4af-45fa-918a-340b085b25cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b195d5d3-51aa-4b45-a9a4-92b66c0a44e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c392e1f1-8aa2-41bd-8e5e-2ec2959a9d7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3efe57fa-504e-4148-b286-0f96883345d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34e996e2-0468-40dc-a594-3a5ee7feaa15</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>14ea7a84-f61e-48c5-ae90-05082951dd0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96a141c5-58d7-4e8b-92de-b2095b91284f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cafd29a7-252c-4a44-ba5e-272351843848</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88c4167e-82c6-4831-8692-d927bcaf2160</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88b25bf2-cc67-49c4-a0ef-1a7ce21de57c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c1e806a-eba8-4dff-a0f3-f9dfe016165d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8b5bc5e-98de-41d4-bc9c-89cd27b58da0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d29f825-c50b-4f52-b10a-5461220fe06f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d5b58d5-32f1-4dcf-852f-316878c61eec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90c1759a-75dc-484c-b917-a56abbe30214</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63351734-046b-45c8-9c42-3072c3924c63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b7c8722-8e7f-4636-85e4-165cd529789e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6c8bc2b-7018-4b36-834e-b39fd103a8ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
