<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GUI_Create_New_Liability</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b5d1fb32-ec2a-4d06-a6d6-cb75683e27ac</testSuiteGuid>
   <testCaseLink>
      <guid>69b37a2c-4bce-4041-931c-202fcf125712</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7c0c096b-2fd9-46cf-a52f-c8d11069ec2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34d15db4-3d96-4881-9f50-1ff79e84beac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95ad5f1b-7284-419d-943c-0c2cda7e5cd3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>860abddc-010d-48cf-a788-a1ae6f92e31c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af93ae93-c3d7-42ac-ad99-82044f425bb7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58dd974b-56e2-4618-a691-e04375be9577</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b8686c6-1c39-4189-a21b-ab087d62f05c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd70f320-db97-49c7-b07f-15df3fb3b903</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>849e19c0-08d0-4eb2-9c7e-da037a30fe08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2345f06b-5545-4457-b5f6-6b9d0a36f169</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e86405e-48ef-486c-8cbc-8d45ec2837fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1b2963b-0a9b-4665-9818-3bfdfc897556</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ada5b7ac-9ccc-40e3-8771-65bea8d987e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f4bb175-dc8d-4afc-9325-92b1ad61f0c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8894c40b-d5e7-4edc-af3c-649ce99973b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a68ab2c-d085-4e82-aacd-ae3d6e1b72a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65b7760f-fe25-4d88-975b-c4817402b150</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f783129f-281e-4030-8fbf-3391c4856333</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e06d0ba1-0bd5-4a47-81c8-162000abd4c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>560b697c-c5be-4adb-9c1e-49951d4d25df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2db137f9-b508-4674-9c34-8ab57493f173</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bda21dde-8579-47e0-a82d-43d619b0dbfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56ca559b-47a7-4a77-8602-2d594991f674</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87c5ef4a-5a50-4a27-b0b9-76654dbc8e37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8db86c7c-e23f-4dec-b6b3-d2a80ca6fff3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c51dfd-8d85-4695-a3c2-1fc0ab8077bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38dcffd3-2bb1-4c33-a808-fa22b1d3efe1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>061c2106-24ae-4fbc-9dd9-f65699b04745</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>add31f1e-11ff-4e34-8001-813fd3c6f05d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ef63971-7faf-4114-b457-4ed277efa811</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36de85d7-8d2d-4479-8bee-2875fa8c2e76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2afbd0c-0fee-4331-9577-6fe36ee662dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8edfe0c9-e175-4946-b301-824f3ed3b996</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>917c527a-c215-40b2-86c1-2ccc0155a7da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7b9108a-820f-4d64-b81f-18c6301d7fbf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebcb457f-e0a8-4557-bb12-815fc92163bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc803c40-2a36-4270-9454-95cd66d1db3b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>843125fc-10bf-49bf-b78e-a3ae6df9d9f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>175c8403-7492-4559-a448-be99a5a3d334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84e60649-77d6-4091-8a79-9c31264b34ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c80504b5-3cb2-4d31-8d27-f9811c8eb3fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>741ba6d4-ad04-45b0-a752-c96f2bad3306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73a88a26-b9f4-4a18-a41f-28a0692c46fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd54c283-6a7e-4f2b-966a-fb670dd3f814</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.16</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a64cbab-4b78-4c63-ba4d-0539ab91c4ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>092bfce6-2f31-4457-a347-7a43bc3cb4f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad3e0b73-4bec-4243-98d9-a3378ffc42e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.17</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
