<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Apply_introjs-overlay</name>
   <tag></tag>
   <elementGuidId>214c866b-a13b-4f90-9319-5d150b75ebf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.introjs-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>144fca6c-84ab-4d44-82a4-061e537de1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>introjs-overlay</value>
      <webElementGuid>4864d757-3e93-4b38-9a06-369b3fcace86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;skin-firefly-iii sidebar-mini&quot;]/div[@class=&quot;introjs-overlay&quot;]</value>
      <webElementGuid>22a71630-dac2-4e59-b5d3-0d5712de15ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>2514bd8c-50c4-4342-8291-dccfcfdb8251</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
