<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Include in net worth_include_net_worth</name>
   <tag></tag>
   <elementGuidId>f7b1abb7-8cd0-48b5-98e4-a8202629c2fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_include_net_worth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_include_net_worth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f4a66e1-bc61-4cd1-9a90-85707032fcc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>54df60b5-1328-4e76-a80c-1112af048c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>include_net_worth</value>
      <webElementGuid>101b600c-5852-4fc7-8e00-d4a1a85f76f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_include_net_worth</value>
      <webElementGuid>c4954eea-2d6f-4e87-893e-86fdd242f261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>55056b35-e808-46dd-ab15-98de58ab17e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_include_net_worth&quot;)</value>
      <webElementGuid>2e2eb2b2-7228-45cc-9d4f-b7c7fcd31989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_include_net_worth']</value>
      <webElementGuid>32a1a5b1-2aeb-4bce-b99c-fffae494507e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='include_net_worth_holder']/div/div/label/input</value>
      <webElementGuid>b1401659-5003-4282-ab55-b9ac72e1dc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>090a2414-7799-4eb4-ab07-d3c4d46edb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'include_net_worth' and @id = 'ffInput_include_net_worth']</value>
      <webElementGuid>82d936b5-4e9b-4c09-9636-1a389c34d20d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
