<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_After storing, return here to create _4fc2e2</name>
   <tag></tag>
   <elementGuidId>832eef21-bcf7-4456-8790-05051a6ac3af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account_return_to_form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account_return_to_form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbb939e2-32ff-4e09-873f-d887e4939a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>867e7740-9471-4e0f-9a1f-bc45ac1d5deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create_another</value>
      <webElementGuid>fa8e5652-eda6-4915-b7ee-6f978d3bcc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account_return_to_form</value>
      <webElementGuid>e9b55d1c-dae9-41e5-9e44-281ee40176af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>376df2c9-796b-47d3-a8b2-30818c3df95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_return_to_form&quot;)</value>
      <webElementGuid>25c8b28e-7869-4372-b90d-01628f22be36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account_return_to_form']</value>
      <webElementGuid>7aaf4b10-341a-47b9-a09c-6c7a099036c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[2]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>fae35881-a242-4528-aafc-42b16d5ed1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>b946d4a1-47c2-4ac3-a49f-8d0935bd475d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'create_another' and @id = 'account_return_to_form']</value>
      <webElementGuid>da923fa4-ddb1-4528-b278-d5fee2600d8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
