<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_demofirefly_fa fa-plus-circle</name>
   <tag></tag>
   <elementGuidId>ab9eb286-e3a8-4cb7-b082-53c7e9c6d5b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-plus-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sidebar-toggle']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>411a298a-5091-4306-8e4f-285c8408cbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle</value>
      <webElementGuid>1208f75a-1f45-4977-a474-05ff4724a954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-toggle&quot;)/a[1]/span[@class=&quot;fa fa-plus-circle&quot;]</value>
      <webElementGuid>ef94e8a1-a7bc-45f2-a746-6e7d012feec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sidebar-toggle']/a/span</value>
      <webElementGuid>7cbcb305-1eb6-428a-acec-b4b1259aee61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>5004c9d6-21fb-419c-9cf9-1e78749efdbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
