<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_demofirefly_fa fa-plus-circle</name>
   <tag></tag>
   <elementGuidId>b3677666-6f89-4242-bbb6-e1258e83e8dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-plus-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sidebar-toggle']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>95c5d5b3-590b-4f94-8713-172425ff9f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle</value>
      <webElementGuid>e31902e9-3488-4247-8b97-8c43cb4ac435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-toggle&quot;)/a[1]/span[@class=&quot;fa fa-plus-circle&quot;]</value>
      <webElementGuid>940a526e-cddb-4c8f-81b3-4594a8c8e8c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sidebar-toggle']/a/span</value>
      <webElementGuid>6a92866a-40f2-4d84-bae4-e52429501932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>40c176f8-4498-493b-b5fb-3f3617dd5645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
