<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_I owe this debt to somebody elseI am_93cb18</name>
   <tag></tag>
   <elementGuidId>2a961d6a-ce5f-481c-8739-2b5fadc46903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_liability_direction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_liability_direction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>00e1d4c4-f351-4bfb-880f-83a194ff1f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bf27c777-e188-4daf-bd65-6298f0c0436f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>liability_direction</value>
      <webElementGuid>77ad107c-9949-49b5-946f-cf148fa24111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_liability_direction</value>
      <webElementGuid>7ea45bf6-750d-410d-9ae2-27d9f2799ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d90ec7c3-3c2a-4244-b102-14d095501ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>022bc9d2-b64a-4f5e-a411-33b680163248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I owe this debt to somebody elseI am owed this debt</value>
      <webElementGuid>c4174c0f-3925-4b0e-9e44-fa2b745642a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_liability_direction&quot;)</value>
      <webElementGuid>68d8ce4b-7413-4e85-b4ab-6ade411cc87a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_liability_direction']</value>
      <webElementGuid>f9bb2c2b-7f8f-4534-95b6-b21ca8bd9af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liability_direction_holder']/div/select</value>
      <webElementGuid>195f903a-2f66-4d3e-a118-61ae8cfeae35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liability in/out'])[1]/following::select[1]</value>
      <webElementGuid>77cab5b5-5f47-49d8-8888-e734005b6cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I owe amount'])[1]/following::select[1]</value>
      <webElementGuid>16578e7e-62f5-4345-a195-3af1fb1ccfbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date of debt'])[1]/preceding::select[1]</value>
      <webElementGuid>0012fbf3-3681-4b9b-a10a-8dc3dcef0694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest'])[1]/preceding::select[1]</value>
      <webElementGuid>e19347fc-24e0-4ebd-925a-4da2eb0759b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>71d0ad89-0154-463f-a7c2-b7abb23db195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'liability_direction' and @id = 'ffInput_liability_direction' and (text() = 'I owe this debt to somebody elseI am owed this debt' or . = 'I owe this debt to somebody elseI am owed this debt')]</value>
      <webElementGuid>2a372efd-f32f-42fe-a4ea-9e99a2efa4c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
